option(FSTM_USE_SIMD_AVX2 "Enable compilation with AVX2 support" OFF)
option(FSTM_USE_SIMD_AVX  "Enable compilation with AVX support" OFF)
option(FSTM_USE_SIMD_SSE42  "Enable compilation with SSE4.2 support" ON)

if (FSTM_USE_SIMD_AVX2)
    message(STATUS "Firestorm: Build with AVX2 support")
    set(__AVX2__ 1)
    add_definitions(-DAVX_VERSION=2)

    if((CMAKE_CXX_COMPILER_ID MATCHES "Clang") OR (CMAKE_CXX_COMPILER_ID MATCHES "GNU"))
        add_compile_options(-mavx2)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        add_compile_options(/arch:AVX)
    endif()
elseif (FSTM_USE_SIMD_AVX)
    message(STATUS "Firestorm: Build with AVX support")
    set(__AVX__ 1)
    add_definitions(-DAVX_VERSION=1)

    if((CMAKE_CXX_COMPILER_ID MATCHES "Clang") OR (CMAKE_CXX_COMPILER_ID MATCHES "GNU"))
        add_compile_options(-mavx)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        add_compile_options(/arch:AVX)
    endif()
endif()

if (FSTM_USE_SIMD_SSE42)
    message(STATUS "Firestorm: Build with SSE 4.2 support")
    set(__SSE__ 42)
    add_definitions(-DSSE_VERSION=4)

    if((CMAKE_CXX_COMPILER_ID MATCHES "Clang") OR (CMAKE_CXX_COMPILER_ID MATCHES "GNU"))
        add_compile_options(-msse4.2)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        message(FATAL "SSE 4.2 support is not available on the MSVC compiler.")
    endif()
endif()