option(FSTM_USE_SIMD_AVX2 "Enable compilation with AVX2 support" OFF)
option(FSTM_USE_SIMD_AVX  "Enable compilation with AVX support" OFF)
if (FSTM_USE_SIMD_AVX2)
    message(STATUS "Firestorm: Build with AVX2 support")
    set(__AVX2__ 1)
    add_definitions(-DAVX_VERSION=2)

    if((CMAKE_CXX_COMPILER_ID MATCHES "Clang") OR (CMAKE_CXX_COMPILER_ID MATCHES "GNU"))
        add_compile_options(-mavx2)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        add_compile_options(/arch:AVX)
    endif()
elseif (FSTM_USE_SIMD_AVX)
    message(STATUS "Firestorm: Build with AVX support")
    set(__AVX__ 1)
    add_definitions(-DAVX_VERSION=1)

    if((CMAKE_CXX_COMPILER_ID MATCHES "Clang") OR (CMAKE_CXX_COMPILER_ID MATCHES "GNU"))
        add_compile_options(-mavx)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        add_compile_options(/arch:AVX)
    endif()
endif()