find_program(CCACHE_FOUND ccache)
option(FSTM_ENABLE_CCACHE "Enables ccache support when building." ON)

if(FSTM_ENABLE_CCACHE)
    if (CCACHE_FOUND)
        message(STATUS "Firestorm: Enabling ccache builds")
        set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
        set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
    else()
        message(STATUS "Firestorm: Not using build cache (ccache not found).")
    endif()
endif()